version: '3'

services:
  nginx:
    image: nginx:1.16
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./www:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/options-ssl-nginx.conf:/etc/nginx/conf.d/options-ssl-nginx.conf
      - ./nginx/htpasswd:/etc/nginx/htpasswd
      - ./certbot:/etc/letsencrypt
    depends_on:
      - php

  php:
    build:
      context: ./php
    restart: unless-stopped
    volumes:
      - ./www:/usr/share/nginx/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/config:/etc/mysql/
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
      - TZ=Europe/Moscow
    command: '--default-authentication-plugin=mysql_native_password'

  certbot:
    depends_on:
      - nginx
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot:/etc/letsencrypt
      - ./www:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email <email> --agree-tos --no-eff-email -d <server>
    # --force-renewal

  wcsync:
    build:
      context: ./wcsync
    depends_on:
      - db
    env_file: .env
